///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesArea = 'assets/images/area.png';
  static const String imagesAsr = 'assets/images/asr.png';
  static const String imagesBathroom = 'assets/images/bathroom.png';
  static const String imagesBathroomTub = 'assets/images/bathroom_tub.png';
  static const String imagesBed = 'assets/images/bed.png';
  static const String imagesBedroom = 'assets/images/bedroom.png';
  static const String imagesCalendar = 'assets/images/calendar.png';
  static const String imagesCall = 'assets/images/call.png';
  static const String imagesConcierge = 'assets/images/concierge.png';
  static const String imagesDuhr = 'assets/images/duhr.png';
  static const String imagesElevator = 'assets/images/elevator.png';
  static const String imagesEmail = 'assets/images/email.png';
  static const String imagesEvents = 'assets/images/events.png';
  static const String imagesEyeAdd = 'assets/images/eye_add.png';
  static const String imagesFajr = 'assets/images/fajr.png';
  static const String imagesGlobal = 'assets/images/global.png';
  static const String imagesGym = 'assets/images/gym.png';
  static const String imagesHome = 'assets/images/home.png';
  static const String imagesHomeStorage = 'assets/images/home_storage.png';
  static const String imagesIsha = 'assets/images/isha.png';
  static const String imagesJumma = 'assets/images/jumma.png';
  static const String imagesLocation = 'assets/images/location.png';
  static const String imagesMaghrib = 'assets/images/maghrib.png';
  static const String imagesMasjid = 'assets/images/masjid.png';
  static const String imagesMenu = 'assets/images/menu.png';
  static const String imagesMessages = 'assets/images/messages.png';
  static const String imagesParking = 'assets/images/parking.png';
  static const String imagesPet = 'assets/images/pet.png';
  static const String imagesPrayerTimings = 'assets/images/prayer_timings.png';
  static const String imagesProfile = 'assets/images/profile.png';
  static const String imagesRamp = 'assets/images/ramp.png';
  static const String imagesSun = 'assets/images/sun.png';
  static const String imagesSwim = 'assets/images/swim.png';
  static const String imagesTag = 'assets/images/tag.png';
  static const String imagesUserSecurity = 'assets/images/user_security.png';
  static const String imagesWashroom = 'assets/images/washroom.png';

}
